/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import studentmanagement.Student;
import studentmanagement.StudentManagement;


/**
 *
 * @author Teka
 */
public class MainFrame extends javax.swing.JFrame {
    StudentManagement studentmanagement;
    DefaultTableModel defauTableModel;
    
    
    /**
     * Creates new form Frame
     */
    public MainFrame() {        
        initComponents();
        studentmanagement = new StudentManagement();
        
        defauTableModel = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }            
        };
        studentTable.setModel(defauTableModel);
        
        defauTableModel.addColumn("SID");
        defauTableModel.addColumn("FIRST NAME");
        defauTableModel.addColumn("LAST NAME");
        defauTableModel.addColumn("MAJOR");
        defauTableModel.addColumn("GPA");
        
        setTableData((studentmanagement.getAllStudent()));
        
    }

    public ArrayList<Student> getStudentList() {
        return studentmanagement.getAllStudent();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jSeparator1 = new javax.swing.JSeparator();
        HeaderUILable = new javax.swing.JLabel();
        DeleteStudentButton = new javax.swing.JButton();
        UpdateStudentButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        studentTable = new javax.swing.JTable();
        RefershButton = new javax.swing.JButton();
        AddButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        MessLable = new javax.swing.JLabel();
        StudentSpinner = new javax.swing.JSpinner();
        FindStudentLable = new javax.swing.JLabel();
        OkFindButton = new javax.swing.JButton();
        ShowStudentLable = new javax.swing.JLabel();
        FindIFText = new javax.swing.JTextField();
        SortStudentLable = new javax.swing.JLabel();
        SidRadioButton = new javax.swing.JRadioButton();
        GpaRadioButton = new javax.swing.JRadioButton();
        FNameRadioButton = new javax.swing.JRadioButton();
        SortButton = new javax.swing.JButton();
        AnnouLable = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        HeaderUILable.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        HeaderUILable.setForeground(new java.awt.Color(255, 0, 0));
        HeaderUILable.setText("STUDENT MANAGEMENT");

        DeleteStudentButton.setText("Delete");
        DeleteStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteStudentButtonActionPerformed(evt);
            }
        });

        UpdateStudentButton.setText("Update");
        UpdateStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateStudentButtonActionPerformed(evt);
            }
        });

        studentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        studentTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        studentTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        studentTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(studentTable);

        RefershButton.setText("Refersh");
        RefershButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefershButtonActionPerformed(evt);
            }
        });

        AddButton.setText("Add");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        StudentSpinner.setModel(new javax.swing.SpinnerListModel(new String[] {"Sid", "Major"}));
        StudentSpinner.setToolTipText("");

        FindStudentLable.setText("Find Student By");

        OkFindButton.setText("Ok");
        OkFindButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkFindButtonActionPerformed(evt);
            }
        });

        ShowStudentLable.setText("Student Infomation");

        SortStudentLable.setText("Sort Student By");

        buttonGroup1.add(SidRadioButton);
        SidRadioButton.setText("Sid");

        buttonGroup1.add(GpaRadioButton);
        GpaRadioButton.setText("Gpa");

        buttonGroup1.add(FNameRadioButton);
        FNameRadioButton.setText("First Name");

        SortButton.setText("Sort");
        SortButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SortButtonActionPerformed(evt);
            }
        });

        AnnouLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AnnouLable.setText("Annoument");
        AnnouLable.setToolTipText("");
        AnnouLable.setAutoscrolls(true);
        AnnouLable.setName(""); // NOI18N
        AnnouLable.setRequestFocusEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MessLable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(77, 77, 77))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(RefershButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)
                        .addComponent(DeleteStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)))
                .addComponent(UpdateStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ShowStudentLable, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(FindStudentLable)
                        .addGap(18, 18, 18)
                        .addComponent(StudentSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FindIFText)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OkFindButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addComponent(SortStudentLable)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SidRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GpaRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FNameRadioButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(SortButton)
                        .addGap(116, 116, 116)))
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(HeaderUILable)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(325, 325, 325)
                .addComponent(AnnouLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(327, 327, 327))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(HeaderUILable, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeleteStudentButton)
                    .addComponent(UpdateStudentButton)
                    .addComponent(RefershButton)
                    .addComponent(AddButton))
                .addGap(18, 18, 18)
                .addComponent(AnnouLable)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StudentSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FindStudentLable)
                    .addComponent(OkFindButton)
                    .addComponent(FindIFText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SortStudentLable)
                    .addComponent(SidRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GpaRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FNameRadioButton))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ShowStudentLable)
                    .addComponent(SortButton))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(MessLable))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateStudentButtonActionPerformed
        
        int row = studentTable.getSelectedRow();
        
        if(row == -1)
        {
            JOptionPane.showMessageDialog(MainFrame.this, "Vui Long Chon Student Truoc","Loi",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
                int sid = Integer.parseInt(String.valueOf(studentTable.getValueAt(row, 0)));
                
                new UpdateFrame(sid).setVisible(true);
                dispose();
            
        }
    }//GEN-LAST:event_UpdateStudentButtonActionPerformed

    private void RefershButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefershButtonActionPerformed
        
        
        defauTableModel.setRowCount(0);
        
        studentmanagement.loadFromFile();
        setTableData((studentmanagement.getAllStudent()));
        AnnouLable.setText("Refesh success!");
    }//GEN-LAST:event_RefershButtonActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        // TODO add your handling code here:
        new AddFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AddButtonActionPerformed

    private void DeleteStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteStudentButtonActionPerformed
        // TODO add your handling code here:
        int row = studentTable.getSelectedRow();
        
        if(row == -1)
        {
            JOptionPane.showMessageDialog(MainFrame.this, "Vui Long Chon Student Truoc","Loi",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            int submit = JOptionPane.showConfirmDialog(MainFrame.this, "Ban Co Chac Chan Muon Xoa Khong?");
            
            if(submit == JOptionPane.YES_OPTION)
            {
                int studentId = Integer.parseInt(String.valueOf(studentTable.getValueAt(row, 0)));
                defauTableModel.setRowCount(0);
                studentmanagement.deleteStudentById(studentId);
                setTableData((studentmanagement.getAllStudent()));
                studentmanagement.saveToFile();
            }
        }
    }//GEN-LAST:event_DeleteStudentButtonActionPerformed

    private void OkFindButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkFindButtonActionPerformed
        // TODO add your handling code here:
        defauTableModel.setRowCount(0);      
        String x =(String) StudentSpinner.getValue();
        if(x.equals("Sid"))
        {
            int sid = Integer.parseInt(FindIFText.getText());
            Student Sid = studentmanagement.findStudentById(sid);
            System.out.println(studentmanagement.findStudentById(sid).toString());
            
            ArrayList<Student> StudentById = new ArrayList();
            StudentById.add(Sid);
            setTableData(StudentById);
            
        }
        
        if(x.equals("Major"))
        { 
            String major = FindIFText.getText();
            ArrayList<Student> StudentByMajor = studentmanagement.findStudentByMajor(major);
            System.out.println(StudentByMajor.toString());
            
            setTableData(StudentByMajor);
        }
       
    }//GEN-LAST:event_OkFindButtonActionPerformed

    private void SortButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SortButtonActionPerformed
        // TODO add your handling code here:
        
        if(SidRadioButton.isSelected())
        {
            studentmanagement.sortById();
        }
        if(GpaRadioButton.isSelected())
        {
            studentmanagement.sortByGpa();
        }
        if(FNameRadioButton.isSelected())
        {
            studentmanagement.sortByFirstName();
        }
        
        defauTableModel.setRowCount(0);      
        setTableData((studentmanagement.getAllStudent()));
    }//GEN-LAST:event_SortButtonActionPerformed
    
    private void setTableData(ArrayList<Student> students)
    {
        for(Student student: students)
        {
            defauTableModel.addRow(new Object[]{student.getSid(), student.getFirstName(), 
                student.getLastName(), student.getMajor(), student.getGpa()});
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JLabel AnnouLable;
    private javax.swing.JButton DeleteStudentButton;
    private javax.swing.JRadioButton FNameRadioButton;
    private javax.swing.JTextField FindIFText;
    private javax.swing.JLabel FindStudentLable;
    private javax.swing.JRadioButton GpaRadioButton;
    private javax.swing.JLabel HeaderUILable;
    private javax.swing.JLabel MessLable;
    private javax.swing.JButton OkFindButton;
    private javax.swing.JButton RefershButton;
    private javax.swing.JLabel ShowStudentLable;
    private javax.swing.JRadioButton SidRadioButton;
    private javax.swing.JButton SortButton;
    private javax.swing.JLabel SortStudentLable;
    private javax.swing.JSpinner StudentSpinner;
    private javax.swing.JButton UpdateStudentButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable studentTable;
    // End of variables declaration//GEN-END:variables
}
