/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author Teka
 */

import studentmanagement.Student;
import studentmanagement.StudentManagement;

public class AddFrame extends javax.swing.JFrame {
    StudentManagement studentmanagement;
    Student student;
    /**
     * Creates new form UpdateFrame
     */
    public AddFrame() {
        studentmanagement = new StudentManagement();
        initComponents();
        studentmanagement.loadFromFile();
        
        student = new Student();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HeaderLable = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        SubmidButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        SidText = new javax.swing.JTextField();
        FNameText = new javax.swing.JTextField();
        LNameText = new javax.swing.JTextField();
        MajorText = new javax.swing.JTextField();
        GpaText = new javax.swing.JTextField();
        SubmidButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        HeaderLable.setText("Add more student");

        SubmidButton.setText("Submit");
        SubmidButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmidButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("First Name");

        jLabel2.setText("Sid");

        jLabel3.setText("Last Name");

        jLabel4.setText("Major");

        jLabel5.setText("Gpa");

        SidText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SidTextActionPerformed(evt);
            }
        });

        FNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FNameTextActionPerformed(evt);
            }
        });

        LNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LNameTextActionPerformed(evt);
            }
        });

        MajorText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MajorTextActionPerformed(evt);
            }
        });

        GpaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GpaTextActionPerformed(evt);
            }
        });

        SubmidButton1.setText("Cancel");
        SubmidButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmidButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(HeaderLable))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SidText, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                            .addComponent(FNameText)
                            .addComponent(LNameText)
                            .addComponent(MajorText)
                            .addComponent(GpaText)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(SubmidButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                        .addComponent(SubmidButton)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(HeaderLable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SidText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(FNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(LNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MajorText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(GpaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SubmidButton)
                    .addComponent(SubmidButton1))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmidButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmidButtonActionPerformed
        
        student.setSid(Integer.parseInt(SidText.getText()));
        student.setFirstName(FNameText.getText());
        student.setLastName(LNameText.getText());
        student.setMajor(MajorText.getText());
        student.setGpa(Float.parseFloat(GpaText.getText()));
       
        studentmanagement.addStudent(student);
        for(Student s: studentmanagement.getAllStudent())
        {
           System.out.println(s); 
        }
        studentmanagement.saveToFile();
       
        new MainFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SubmidButtonActionPerformed

    private void SidTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SidTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SidTextActionPerformed

    private void FNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FNameTextActionPerformed

    private void LNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LNameTextActionPerformed

    private void MajorTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MajorTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MajorTextActionPerformed

    private void GpaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GpaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GpaTextActionPerformed

    private void SubmidButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmidButton1ActionPerformed
        // TODO add your handling code here:
        new MainFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SubmidButton1ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FNameText;
    private javax.swing.JTextField GpaText;
    private javax.swing.JLabel HeaderLable;
    private javax.swing.JTextField LNameText;
    private javax.swing.JTextField MajorText;
    private javax.swing.JTextField SidText;
    private javax.swing.JButton SubmidButton;
    private javax.swing.JButton SubmidButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
